on:
  pull_request_review:
    types: [submitted]

name: release-please
jobs:
  release-please:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: php
          package-name: release-please-action